name       : atool
version    : 0.39.0
release    : 1
source     :
    - http://savannah.nongnu.org/download/atool/atool-0.39.0.tar.gz : aaf60095884abb872e25f8e919a8a63d0dabaeca46faeba87d12812d6efc703b
license    : GPL-2.0
component  : system.utils
summary    : Manage file archives of various types
description: |
   atool is a script for managing file archives of various types (tar, tar+gzip, zip etc). The main command is aunpack which extracts files from an archive 
builddeps  :
   - perl
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
